name: 'Monorepo Split'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # 1. for Github split
  GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLIT_TOKEN }}

jobs:
  split_packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Configuration de tes couples dossier <-> dépôt
        package:
          - { local: 'scraper', remote: 'scraper' }
          - { local: 'scraper-colisprive', remote: 'scraper-colisprive' }
          - { local: 'scraper-colissimo', remote: 'scraper-colissimo' }
          - { local: 'scraper-dpd', remote: 'scraper-dpd' }
          - { local: 'scraper-delivengo', remote: 'scraper-delivengo' }
          - { local: 'scraper-laposte-apim', remote: 'scraper-laposte-apim' }
          - { local: 'scraper-laposte-postage', remote: 'scraper-laposte-postage' }
          - { local: 'scraper-prestashop', remote: 'scraper-prestashop' }
          - { local: 'scraper-tnt', remote: 'scraper-tnt' }
          - { local: 'scraper-ups', remote: 'scraper-ups' }
          - { local: 'scraper-zakeke', remote: 'scraper-zakeke' }
          - { local: 'scraper-compagnie-deboucheurs', remote: 'scraper-compagnie-deboucheurs' }
          - { local: 'scraper-jeudimerci', remote: 'scraper-jeudimerci' }
          - { local: 'scraper-nograd', remote: 'scraper-nograd' }

    steps:
      - name: Check Token
        run: |
          if [ -z "${{ secrets.MONOREPO_SPLIT_TOKEN }}" ]; then
            echo "Le secret MONOREPO_SPLIT_TOKEN est VIDE !"
            exit 1
          fi
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Nécessaire pour reconstruire l'historique sur le miroir

      - name: Split and Push ${{ matrix.package.local }}
        uses: danharrin/monorepo-split-github-action@v2.4.5
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.local }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'rem42'
          repository_name: '${{ matrix.package.remote }}'

          # ↓ the user signed under the split commit
          user_name: "rem42"
          user_email: "me@remy.ovh"
